sy_tutos:
    path:     /tutoriels/{category}
    defaults:
        _controller:  SyTutoBundle:Tuto:index
        category:     all

sy_tuto:
    path:     /tutoriel/{slug}
    defaults:
        _controller: SyTutoBundle:Tuto:view

sy_addTuto:
    path:     /add/
    defaults:
        _controller: SyTutoBundle:Tuto:addTuto

sy_editTuto:
    path:     /edit/{id}
    defaults:
        _controller: SyTutoBundle:Tuto:editTuto
    requirements :
        id : '\d+'

