sy_tutos:
    path:     /list/{category}/{page}
    defaults:
        _controller:  SyTutoBundle:Tuto:index
        category:     all
        page: 1
    requirements:
        page: \d*

sy_addTuto:
    path:     /add/
    defaults:
        _controller: SyTutoBundle:Tuto:addTuto

sy_editTuto:
    path:     /edit/{id}
    defaults:
        _controller: SyTutoBundle:Tuto:editTuto
    requirements :
        id : '\d+'

sy_tuto:
    path:     /{slug}
    defaults:
        _controller: SyTutoBundle:Tuto:view
