<?php

namespace Sy\MainBundle\Repository;

/**
 * GroupClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupClassRepository extends \Doctrine\ORM\EntityRepository
{
}
