sy_tuto:
    resource: "@SyTutoBundle/Resources/config/routing.yml"
    prefix:   /

sy_main:
    resource: "@SyMainBundle/Resources/config/routing.yml"
    prefix:   /

sy_agenda:
    resource: "@SyAgendaBundle/Resources/config/routing.yml"
    prefix:   /agenda

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"