<?php

namespace Sy\TutoBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TutorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorialRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTutos($groups, $page, $nbPerPage){
        $qry = $this->createQueryBuilder('t')
            ->leftJoin('t.groups', 'g')
            ->andWhere('t.fullVisibility = true')
            ->orWhere('g IN (:userGroups)')
            ->setParameter('userGroups', $groups)
            ->orderBy('t.date', 'DESC')
            ->getQuery();

        $qry->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($qry, true);
    }
    public function findByCategory($groups, $category, $page, $nbPerPage){
        $qry = $this->createQueryBuilder('t')
            ->leftJoin('t.categories', 'c')
            ->addSelect('c')
            ->leftJoin('t.groups', 'g')
            ->andWhere('t.fullVisibility = true')
            ->orWhere('g IN (:userGroups)')
            ->andWhere('c.slug = :category')
            ->setParameter('userGroups', $groups)
            ->setParameter('category', $category)
            ->orderBy('t.date', 'DESC')
            ->getQuery();

        $qry->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($qry, true);
    }

}
