<?php

namespace Sy\TutoBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TutorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorialRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTutos($groups, $page, $nbPerPage){
        $qry = $this->createQueryBuilder('t')
            ->leftJoin('t.author', 'u')
            ->addSelect('u')
            ->leftJoin('u.groupClasses', 'g')
            ->addSelect('g')
            ->andWhere('t.fullVisibility = true')
            ->orWhere("g = '".$groups."'")
            ->orderBy('t.date', 'DESC')
            ->getQuery();

        $qry->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($qry, true);
    }
    public function findByCategory($groups, $category, $page, $nbPerPage){
        $qry = $this->createQueryBuilder('t')
            ->leftJoin('t.categories', 'c')
            ->addSelect('c')
            ->leftJoin('t.author', 'u')
            ->addSelect('u')
            ->leftJoin('u.classroom', 'cl')
            ->addSelect('cl')
            ->andWhere('t.fullVisibility = true')
            ->orWhere("cl.name = '".$groups."'")
            ->andWhere("c.slug = '".$category."'")
            ->orderBy('t.date', 'DESC')
            ->getQuery();

        $qry->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($qry, true);
    }

}
