<?php

namespace Sy\AgendaBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGroups($groups)
    {
        $qry = $this-> createQueryBuilder('p')
            ->andWhere("p.group IN (:groups)")
            ->setParameter('groups', $groups)
            ->getQuery()
            ->getResult();

        return $qry;
    }
}
