sy_forum:
    path:     /list/{category}/{page}
    defaults:
        _controller:  SyForumBundle:Forum:index
        category:     all
        page: 1
    requirements:
        page: \d*

sy_post:
    path:   /post/{slug}
    defaults:
        _controller: SyForumBundle:Forum:view

sy_add_post:
    path:   /add
    defaults:
        _controller: SyForumBundle:Forum:add

sy_edit_post:
    path:   /edit/{id}
    defaults:
        _controller: SyForumBundle:Forum:edit
    requirements :
            id : '\d+'

sy_add_like:
    path: /like-request
    defaults:
        _controller: SyForumBundle:Forum:vote